// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  ExtractPdfChunksData,
  ExtractPdfChunksErrors,
  ExtractPdfChunksResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Extract Pdf Chunks
 *
 * Upload a PDF file and receive contextualized chunks.
 *
 * Returns a list of chunks with original text, contextualized text, and metadata.
 */
export const extractPdfChunks = <ThrowOnError extends boolean = false>(
  options: Options<ExtractPdfChunksData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ExtractPdfChunksResponses,
    ExtractPdfChunksErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    url: "/pdf/chunks",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });
