// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  ProcessPdfDocumentData,
  ProcessPdfDocumentErrors,
  ProcessPdfDocumentResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Process Pdf Document
 *
 * Upload a PDF file and receive processed document with chunks, embeddings, and full text.
 *
 * Returns:
 * - List of chunks with original text, contextualized text, embeddings, and metadata
 * - Full text of the document
 * - Total chunk count
 */
export const processPdfDocument = <ThrowOnError extends boolean = true>(
  options: Options<ProcessPdfDocumentData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ProcessPdfDocumentResponses,
    ProcessPdfDocumentErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    url: "/pdf/process",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });
