// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8000" | (string & {});
};

/**
 * Body_process_pdf_document
 */
export type BodyProcessPdfDocument = {
  /**
   * File
   *
   * PDF file to process
   */
  file: Blob | File;
};

/**
 * ChunkResponse
 */
export type ChunkResponse = {
  /**
   * Text
   */
  text: string;
  /**
   * Contextualized Text
   */
  contextualized_text: string;
  /**
   * Embedding
   */
  embedding: Array<number>;
  /**
   * Index
   */
  index: number;
  /**
   * Meta
   */
  meta: {
    [key: string]: unknown;
  };
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
  /**
   * Detail
   */
  detail: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * ProcessedDocumentResponse
 */
export type ProcessedDocumentResponse = {
  /**
   * Chunks
   */
  chunks: Array<ChunkResponse>;
  /**
   * Total Chunks
   */
  total_chunks: number;
  /**
   * Full Text
   */
  full_text: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type ProcessPdfDocumentData = {
  body: BodyProcessPdfDocument;
  path?: never;
  query?: never;
  url: "/pdf/process";
};

export type ProcessPdfDocumentErrors = {
  /**
   * Bad Request - Invalid file format
   */
  400: ErrorResponse;
  /**
   * Validation Error
   */
  422: HttpValidationError;
  /**
   * Internal Server Error - Error processing PDF
   */
  500: ErrorResponse;
};

export type ProcessPdfDocumentError =
  ProcessPdfDocumentErrors[keyof ProcessPdfDocumentErrors];

export type ProcessPdfDocumentResponses = {
  /**
   * Successful Response
   */
  200: ProcessedDocumentResponse;
};

export type ProcessPdfDocumentResponse =
  ProcessPdfDocumentResponses[keyof ProcessPdfDocumentResponses];
