// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8000" | (string & {});
};

/**
 * Body_extract_pdf_chunks
 */
export type BodyExtractPdfChunks = {
  /**
   * File
   *
   * PDF file to process
   */
  file: Blob | File;
};

/**
 * ChunkResponse
 */
export type ChunkResponse = {
  /**
   * Text
   */
  text: string;
  /**
   * Contextualized Text
   */
  contextualized_text: string;
  /**
   * Meta
   */
  meta: {
    [key: string]: unknown;
  };
};

/**
 * ChunksResponse
 */
export type ChunksResponse = {
  /**
   * Chunks
   */
  chunks: Array<ChunkResponse>;
  /**
   * Total Chunks
   */
  total_chunks: number;
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
  /**
   * Detail
   */
  detail: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type ExtractPdfChunksData = {
  body: BodyExtractPdfChunks;
  path?: never;
  query?: never;
  url: "/pdf/chunks";
};

export type ExtractPdfChunksErrors = {
  /**
   * Bad Request - Invalid file format
   */
  400: ErrorResponse;
  /**
   * Validation Error
   */
  422: HttpValidationError;
  /**
   * Internal Server Error - Error processing PDF
   */
  500: ErrorResponse;
};

export type ExtractPdfChunksError =
  ExtractPdfChunksErrors[keyof ExtractPdfChunksErrors];

export type ExtractPdfChunksResponses = {
  /**
   * Successful Response
   */
  200: ChunksResponse;
};

export type ExtractPdfChunksResponse =
  ExtractPdfChunksResponses[keyof ExtractPdfChunksResponses];
